# Generated by Django 5.2.1 on 2025-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_actualmodel_errorcode_settings_user_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bitrix_lead_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
