# Generated by Django 5.2.1 on 2026-04-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_user_bitrix_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page', models.CharField(default='Главная страница', max_length=255, verbose_name='Текст после команды старт')),
                ('want_dealer', models.CharField(default='Хочу стать дилером', max_length=255, verbose_name='Кнопка: Хочу стать дилером')),
                ('service_request', models.CharField(default='Отправить запрос в сервисный центр', max_length=255, verbose_name='Кнопка: Не работает кондиционер')),
                ('dealer_brand_question', models.TextField(default='1. Стать дилером какого бренда вы хотите?\n(GREE, KITANO, ROVER)', verbose_name='Вопрос: Выбор бренда для дилерства')),
                ('dealer_info_question', models.TextField(default='2. Укажите название компании, адрес, ваше ФИО, номер телефона для связи, адрес электронной почты, сайт если есть', verbose_name='Вопрос: Данные будущего дилера')),
                ('dealer_manager_contact', models.TextField(default='Менеджер с вами свяжется в ближайшее время', verbose_name='Сообщение: Менеджер свяжется (дилер)')),
                ('role_selection', models.TextField(default='Кем вы являетесь?', verbose_name='Вопрос: Выбор роли пользователя')),
                ('role_company_btn', models.CharField(default='Климатическая компания/монтажная организация', max_length=255, verbose_name='Кнопка: Климатическая компания')),
                ('role_consumer_btn', models.CharField(default='Конечный потребитель', max_length=255, verbose_name='Кнопка: Конечный потребитель')),
                ('consumer_info', models.TextField(default='Если у вас не работает кондиционер, вы можете обратиться в компанию у которой вы преобретали оборудование или оставить заявку в нашем сервисе и мы сами свяжемся с компанией у которой вы приобрели оборудование', verbose_name='Сообщение: Инфо для конечного потребителя')),
                ('consumer_contact_myself_btn', models.CharField(default='Свяжусь сам', max_length=255, verbose_name='Кнопка: Свяжусь сам')),
                ('consumer_leave_request_btn', models.CharField(default='Оставлю заявку вам', max_length=255, verbose_name='Кнопка: Оставлю заявку вам')),
                ('consumer_contact_details', models.TextField(default='Укажите ваше ФИО, номер телефона для связи и адрес электронной почты.', verbose_name='Вопрос: Контакты потребителя')),
                ('consumer_barcode_request', models.TextField(default='Пожалуйста, приложите фотографию штрихкода с оборудования, которое вышло из строя', verbose_name='Запрос: Фото штрихкода потребителя')),
                ('consumer_final_thanks', models.TextField(default='Спасибо за обращение в нашу компанию, ваша заявка будет передана в ближайшее время.', verbose_name='Сообщение: Заявка потребителя принята')),
                ('company_details_request', models.TextField(default='Укажите Название компании, адрес, ваше ФИО, номер телефона для связи и адрес электронной почты.', verbose_name='Вопрос: Данные климатической компании')),
                ('is_our_dealer_question', models.TextField(default='Являетесь ли вы нашим дилером?', verbose_name='Вопрос: Являетесь ли нашим дилером?')),
                ('object_address_request', models.TextField(default='2. Укажите адрес и название объекта (должна быть возможность пропустить этот вопрос)', verbose_name='Вопрос: Адрес и название объекта')),
                ('action_claim_btn', models.CharField(default='Отправить запрос по рекламации в сервисный центр', max_length=255, verbose_name='Кнопка: Запрос по рекламации')),
                ('action_errors_btn', models.CharField(default='Справимся сами. Нужны коды ошибок.', max_length=255, verbose_name='Кнопка: Нужны коды ошибок')),
                ('action_manuals_btn', models.CharField(default='Нужны инструкции по оборудованию или по монтажу', max_length=255, verbose_name='Кнопка: Нужны инструкции')),
                ('select_brand', models.TextField(default='Выберите бренд кондиционера (Gree, Kitano, Rover и тп)', verbose_name='Вопрос: Выбор бренда оборудования')),
                ('select_type', models.TextField(default='Выберите тип кондиционера (Бытовые, полупромышленные, мультизональные)', verbose_name='Вопрос: Выбор типа оборудования')),
                ('select_series', models.TextField(default='Выберите серию кондиционера', verbose_name='Вопрос: Выбор серии')),
                ('model_not_in_list', models.CharField(default='Варианта нет в списке (Модель снята с производства)', max_length=255, verbose_name='Кнопка: Модели нет в списке')),
                ('input_brand_model', models.TextField(default='Укажите марку и модель кондиционера.', verbose_name='Запрос: Ввод марки и модели вручную')),
                ('purchase_date_invoice', models.TextField(default='Укажите дату покупки оборудования или номер счета', verbose_name='Запрос: Дата покупки / номер счета')),
                ('error_codes_info', models.TextField(default='Коды ошибок. Обычные коды ошибок - информация из инструкции. Расширенные коды ошибок - расширенная информация из сервис мануала', verbose_name='Инфо: Сообщение с кодами ошибок')),
                ('error_not_in_list', models.CharField(default='В списке нет нужной ошибки', max_length=255, verbose_name='Кнопка: Нужной ошибки нет')),
                ('manual_not_in_list', models.CharField(default='В списке нет нужной инструкции', max_length=255, verbose_name='Кнопка: Нужной инструкции нет')),
                ('error_provide_barcode', models.TextField(default='Если есть возможность, пришлите штрихкод или фото штрихкода.', verbose_name='Запрос: Пришлите фото штрихкода (для ошибок)')),
                ('redirect_to_claim', models.TextField(default='Так как в списке нет нужного варианта, мы предлагаем вам отправить запрос в сервисный центр', verbose_name='Сообщение: Перевод на создание рекламации')),
                ('claim_act_question', models.TextField(default='У вас есть возможность заполнить и отправить акт о неисправности?', verbose_name='Вопрос: Наличие акта неисправности')),
                ('claim_send_act', models.TextField(default='Заполните акт и отправьте его сюда', verbose_name='Запрос: Отправка акта')),
                ('claim_barcode', models.TextField(default='Если есть возможность, пришлите номер штрихкода / фотографию штрихкода.', verbose_name='Запрос: Фото штрихкода (рекламация)')),
                ('claim_diagnostics', models.TextField(default='Вы проводили первичную диагностику?', verbose_name='Вопрос: Первичная диагностика')),
                ('claim_diagnostics_results', models.TextField(default='Какие результаты диагностики?', verbose_name='Запрос: Результаты диагностики')),
                ('claim_error_code', models.TextField(default='Какой код ошибки высвечивается на дисплее кондиционера. Если есть возможность, пришлите фотографию.', verbose_name='Запрос: Код ошибки (рекламация)')),
                ('claim_what_did_you_do', models.TextField(default='Что вы делали? Если есть возможность, пришлите видео и фотографии', verbose_name='Запрос: Что вы делали (рекламация)')),
                ('claim_all_data_provided', models.TextField(default='Вы указали все запрашиваемые данные?', verbose_name='Вопрос: Все ли данные указаны')),
                ('claim_provide_all_data', models.TextField(default='Пожалуйста, укажите все запрашиваемые данные. Если вы заполнили не все данные, мы не сможем с вами связаться.', verbose_name='Сообщение: Укажите все данные')),
                ('claim_tech_question', models.TextField(default='Отправьте ваш вопрос техническому специалисту', verbose_name='Запрос: Вопрос тех. специалисту')),
                ('request_in_work', models.TextField(default='Ваш запрос в работе. Менеджер сервиса ответит вам в ближайшее время.', verbose_name='Сообщение: Запрос в работе')),
                ('more_questions', models.TextField(default='У вас еще есть вопросы по этой неисправности?', verbose_name='Вопрос: Есть ли еще вопросы')),
                ('auto_close_ticket', models.TextField(default='Если вопросов нет в течении 24 часов, заявка автоматически закрывается', verbose_name='Сообщение: Автозакрытие заявки')),
                ('thanks_for_contacting', models.TextField(default='Спасибо за обращение в нашу компанию', verbose_name='Сообщение: Спасибо за обращение')),
                ('btn_yes', models.CharField(default='ДА', max_length=50, verbose_name='Кнопка: ДА')),
                ('btn_no', models.CharField(default='НЕТ', max_length=50, verbose_name='Кнопка: НЕТ')),
            ],
            options={
                'verbose_name': 'Тексты бота (Все сообщения)',
                'verbose_name_plural': 'Тексты бота (Все сообщения)',
            },
        ),
        migrations.AddField(
            model_name='actualmodel',
            name='manual_install',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='web/media/manuals/install', verbose_name='Инструкция по монтажу'),
        ),
        migrations.AddField(
            model_name='actualmodel',
            name='manual_user',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='web/media/manuals/user', verbose_name='Инструкция пользователя'),
        ),
        migrations.CreateModel(
            name='GreeManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название инструкции')),
                ('file', models.FileField(upload_to='manuals/gree/', verbose_name='Файл инструкции')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='panel.greemodel', verbose_name='Модель кондиционера')),
            ],
            options={
                'verbose_name': 'Инструкция Gree',
                'verbose_name_plural': 'Инструкции Gree',
            },
        ),
        migrations.CreateModel(
            name='KitanoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название инструкции')),
                ('file', models.FileField(upload_to='manuals/kitano/', verbose_name='Файл инструкции')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='panel.kitanomodel', verbose_name='Модель кондиционера')),
            ],
            options={
                'verbose_name': 'Инструкция Kitano',
                'verbose_name_plural': 'Инструкции Kitano',
            },
        ),
        migrations.CreateModel(
            name='RoverManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название инструкции')),
                ('file', models.FileField(upload_to='manuals/rover/', verbose_name='Файл инструкции')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='panel.rovermodel', verbose_name='Модель кондиционера')),
            ],
            options={
                'verbose_name': 'Инструкция Rover',
                'verbose_name_plural': 'Инструкции Rover',
            },
        ),
    ]
